### ISSUE TITLE
NullpointerException occurs on calling findPath

### ISSUE THREAD

**Issue by Sytm** [olijeffers0n/PatheticAPI#21]
RuleSet:
```kotlin
PathingRuleSet.createAsyncRuleSet()
                .withAllowingDiagonal(true)
                .withAllowingFallback(true)
                .withLoadingChunks(false)
                .withAllowingFailFast(true)
                .withStrategy(WalkablePathfinderStrategy::class.java)
```
Stacktrace:
```
[15:52:05 WARN]: [Waypoints] Task #12 for Waypoints v4.0.0-SNAPSHOT generated an exception
java.lang.NullPointerException: Cannot invoke "org.patheloper.api.wrapper.PathBlock.isPassable()" because "pathBlock" is null
	at org.patheloper.model.pathing.pathfinder.AbstractPathfinder.isBlockUnreachable(AbstractPathfinder.java:121) ~[waypoints-4.0.0-SNAPSHOT.jar:?]
	at org.patheloper.model.pathing.pathfinder.AbstractPathfinder.initialChecksFailed(AbstractPathfinder.java:111) ~[waypoints-4.0.0-SNAPSHOT.jar:?]
	at org.patheloper.model.pathing.pathfinder.AbstractPathfinder.findPath(AbstractPathfinder.java:76) ~[waypoints-4.0.0-SNAPSHOT.jar:?]
	at org.patheloper.model.pathing.pathfinder.AStarPathfinder.findPath(AStarPathfinder.java:23) ~[waypoints-4.0.0-SNAPSHOT.jar:?]
	at de.md5lukas.waypoints.pointers.variants.TrailPointer.update(TrailPointer.kt:90) ~[waypoints-4.0.0-SNAPSHOT.jar:?]
	at de.md5lukas.waypoints.pointers.Pointer.show(Pointer.kt:19) ~[waypoints-4.0.0-SNAPSHOT.jar:?]
	at de.md5lukas.waypoints.pointers.ManagedPlayer$PlayerPointer.run(ManagedPlayer.kt:133) ~[waypoints-4.0.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-538]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-538]
```
Both start and stop are < 30 blocks apart and start is the players current position.

It doesn't matter if both blocks are air or set.

It _seems_ to me the FailingSnapshotManager never retrieves chunk snapshots instead of only if they are loaded (as I would expect from the description in the JavaDoc https://patheticdocs.ollieee.xyz/org/patheloper/api/pathing/rules/PathingRuleSet.html)

(And just out of curiosity, why is NMS used to retrieve the ChunkSnapshots and not the Bukkit API?)

**Comment by olijeffers0n** [comment]
I'm working on this. For now, I believe that enabling chunk loading will resolve your issues

**Comment by olijeffers0n** [comment]
See commit https://github.com/patheloper/pathetic/commit/60228a0e43dab5dde8571c84c50da096826ee920

**Comment by olijeffers0n** [comment]
So this is all fixed in 2.1.4. Thank you for bringing this to our attention though!

To address your original comment about us using NMS to access chunk snapshots- it may seem a bit weird. The snapshots are great for when you want to access world data asynchronously however they can only be fetched on the main thread. Us hooking into NMS allows us to bypass the Spigot AsyncCatcher and fetch the snapshots natively from our async context.

Any more questions or issues do let us know

**Comment by Sytm** [comment]
I just noticed that the order of the returned positions of `path.getPositions()` seem a bit odd.
```
[19:36:50 INFO]: Index Position
[19:36:50 INFO]: 0 0.5,98.5,0.5 <-- My start position
[19:36:50 INFO]: 1 0.5,98.5,5.5 <-- My end position
[19:36:50 INFO]: 2 0.5,98.5,4.5
[19:36:50 INFO]: 3 0.5,98.5,3.5
[19:36:50 INFO]: 4 0.5,98.5,2.5
[19:36:50 INFO]: 5 0.5,98.5,1.5
[19:36:50 INFO]: 6 0.5,98.5,0.5 <-- My start position again
```
Although the JavaDoc states noting about the order of the positions (my intuition would have told me that the start would be at the beginning of the iterable), but it seems at the very least kinda weird that the start position appears at the start and end of the iterable.

**Comment by bsommerfeld** [comment]
you're right, it shouldn't be there. probably an ancient code piece that got lost in all the refactorings. will fix it asap, thanks for reporting :)

**Comment by bsommerfeld** [comment]
fix has been backported to 2.1.4. should be available in a few minutes
see: https://github.com/patheloper/pathetic/commit/39a89b1be6353b94f572423e55a28dc0fbcaba13

**Comment by Sytm** [comment]
> The snapshots are great for when you want to access world data asynchronously however they can only be fetched on the main thread. Us hooking into NMS allows us to bypass the Spigot AsyncCatcher and fetch the snapshots natively from our async context.

[Paper has API for that](https://jd.papermc.io/paper/1.19/org/bukkit/World.html#getChunkAtAsyncUrgently(int,int)) with the caveat being that the method itself is now returning a CompletableFuture instead of return the value directly.

I don't know if this is useful for you, because that would require changing the inner workings to accommodate for the CompletableFuture, but it could allow for an "NMS" module that fetches the ChunkSnapshots on Paper without actual NMS code.

**Comment by bsommerfeld** [comment]
> > The snapshots are great for when you want to access world data asynchronously however they can only be fetched on the main thread. Us hooking into NMS allows us to bypass the Spigot AsyncCatcher and fetch the snapshots natively from our async context.
> 
> [Paper has API for that](https://jd.papermc.io/paper/1.19/org/bukkit/World.html#getChunkAtAsyncUrgently(int,int)) with the caveat being that the method itself is now returning a CompletableFuture instead of return the value directly.
> 
> I don't know if this is useful for you, because that would require changing the inner workings to accommodate for the CompletableFuture, but it could allow for an "NMS" module that fetches the ChunkSnapshots on Paper without actual NMS code.

we are aware that the paper api gives us more freedom regarding async operations. however, our primary focus is on spigot and every other fork pathetic works on is a nice addition. we do not want and need a double-edged sword.
