### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by andre-xizto** [olijeffers0n/PatheticAPI#69]
### Stack trace

```
Error occurred while disabling buplugin v1.0-SNAPSHOT
java.lang.NoClassDefFoundError: org/patheloper/mapping/PatheticMapper
        at dev.com.buskopan.buplugin.Buplugin.onDisable(Buplugin.java:84) ~[buplugin-1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[paper-1.20.4.jar:git-Paper-454]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.4.jar:git-Paper-454]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.20.4.jar:git-Paper-454]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-454]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-454]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-454]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.patheloper.mapping.PatheticMapper
        ... 16 more
```

### Other

This is my ```build.gradle```:

```plugins {
    id 'java'
}

group = 'dev.com.buskopan'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven {
        name = "jitpack.io"
        url = 'https://jitpack.io' }
}

jar {
    destinationDirectory.set(file("C:/Users/Andre/Desktop/Server/plugins"))
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT"
    implementation 'com.github.patheloper.pathetic:pathetic-mapping:2.4'
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
```

**Comment by olijeffers0n** [comment]
Hi there, thank you for reporting this! We are both currently away for a day so we can’t solve this immediately - trust us though that we will get to this in due course! Thanks again 🙏

**Comment by andre-xizto** [comment]
> Hi there, thank you for reporting this! We are both currently away for a day so we can’t solve this immediately - trust us though that we will get to this in due course! Thanks again 🙏

No worries, i got it!


But i want to know why pets is not following the player. That's works?

```
org.patheloper.api.pathing.Pathfinder pathfinder;
Player p = (Player) e.getWhoClicked();
Entity pet = null;

switch (e.getCurrentItem().getItemMeta().getDisplayName()) {
                case "§cPorco":
                    pet = p.getWorld().spawnEntity(Objects.requireNonNull(Buplugin.getPluginConfig().getLocation("spawnpoint")), EntityType.PIG);
                    break;
                case "§cGalinha":
                    pet = p.getWorld().spawnEntity(Objects.requireNonNull(Buplugin.getPluginConfig().getLocation("spawnpoint")), EntityType.CHICKEN);
                    break;
            }

PathPosition start = BukkitMapper.toPathPosition(pet.getLocation());
PathPosition target = BukkitMapper.toPathPosition(p.getLocation());

pathfinder = PatheticMapper.newPathfinder();
pathfinder.findPath(start, target, new DirectPathfinderStrategy());

```

Or i need to do more thing?

**Comment by olijeffers0n** [comment]
This simply finds a path, you still need to actually make the entity walk along it manually

**Comment by andre-xizto** [comment]
> This simply finds a path, you still need to actually make the entity walk along it manually

How can i do it?

**Comment by bsommerfeld** [comment]
That functionality is not directly built into pathetic, therefore we can't help you, but offer guidance: You would need to store the Path somewhere and let your entity follow it along with the help of a scheduler. 

Closing this since the original issue is solved.

**Comment by andre-xizto** [comment]
Thank you!
